<a href="https://colab.research.google.com/github/viett887g/vector/blob/main/vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from collections import Counter
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
def cleantext_returnlist(file):
    list1 = []
    temp = []
    for words in file:
        words = words.replace(',','')
        words = words.replace('.','')
        #chia các từ trong list thành từng phần tử dc cách nhau bởi khoảng trắng
        temp_list = words.split()
        temp.append(temp_list)
    #gộp tất cả các dic lại với nhau
    for i in range(len(temp)-1):
        temp[i+1] = temp[i]+temp[i+1]
    return temp[len(temp)-1]

def unique_words(list1):

    # khởi tạo một danh sách rỗng
    unique_list = []
  
    # lượt qua tất cả các phần tử có trong list
    for x in list1:
        # check xem trong list vừa khởi tạo trên có phần tử đấy hay không, nếu không thì thêm vào
        if x not in unique_list:
            unique_list.append(x)
    return unique_list

def initialize_dictionary(file):
    dic = cleantext_returnlist(file)
    dic = unique_words(dic)
    return dic

def count_t_in_d(d):
    #tạo ma trận rỗng để thêm tất cả các từ có trong d 
    array_split = []
    for line in d:
        #lấy từng dòng ở d để thu về một list gồm các từ
        list_words = line.split()

        for m in list_words:
            #bỏ đi các dấu ',','.'
            m = m.strip(',') 
            m = m.strip('.')
            #thêm tất cả các từ vào trong list
            array_split.append(m)

    #dùng hàm Counter để đếm số lần xuất hiện các từ trong văn bản
    counts = dict(Counter(array_split))
    
    return counts

def from_text_return_a_array(file_text,dic):
    #tạo từ điển
    dictionary = initialize_dictionary(dic)
    #khởi tạo danh sách rỗng bằng số chiều với dictionary
    array_null = [0 for x in range(len(dictionary))]
    #tính tần xuất suất hiện của 'từ' trong file
    counts = count_t_in_d(file_text)
    #Gán từng giá trị của biến counts vào danh sách rỗng hồi nãy
    for i in range(len(dictionary)):
        try:
            array_null[i] = counts[dictionary[i]]
        except:
            pass
    return array_null

In [ ]:
def read_file(name_file):
    folder_d = [] #list dùng để lưu các text
    dic_d = [] #list dùng để tạo dictionary
    for i in name_file:
        with open(f'C:/Users/ADMIN/Downloads/corpus-tf-idf/{i}','r',encoding='ISO-8859-1') as f:
            dic = f.read() 
            dic = dic.strip("\n")
        dic_d.append(dic)
        
        with open(f'C:/Users/ADMIN/Downloads/corpus-tf-idf/{i}','r',encoding='ISO-8859-1') as f:
            count = 0
            d = []
            while True:
                count += 1
                line = f.readline()
                if not line:
                    break
                if line == '\n':
                    continue
                d.append(line.strip("\n"))
        folder_d.append(d)
        
    return dic_d, folder_d

In [ ]:
def main():
    arrays = []
    for i in folder_d:
        array = from_text_return_a_array(i,dic_d)
        array = np.array(array) #list to array
        arrays.append(array)
    for i in range(len(arrays)-1):
        arrays[i+1] = np.row_stack((arrays[i],arrays[i+1]))
    print(arrays[len(arrays)-1])
    
main()

[[2 4 3 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
